/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
//    @Test
//    public void testRoll() {
//        Library TestRoll = new Library();
//        int n;
//        n=2;
//        int[] rollArry = Library.roll(n);
//        assertEquals("rollArray values should be  between 1-6", rollArry.length,  n);
//
//    }
//@Test public void testDuplicates(){
//    int[] testArr = new int[]{1,2,3,3};
//
//    assertTrue("Should return true if duplicates exist", Library.containsDuplicates(testArr));
//}
}
