/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Stack;
import java.util.Random;
public class Library {

    public boolean someLibraryMethod() {
        return true;
    }
    public static int[] roll(int n)
    {
        int[] rollArr = new int[n];
        for(int i=0;i<n;i++)
        {
            Random rand = new Random();
            int upperbound = 6;
            int int_random = rand.nextInt(upperbound)+1;
            rollArr[i] = int_random;
        }
        return rollArr;
    }
    public static boolean hasDuplicates(int[] Arr){

        for (int i = 0; i < Arr.length; i++) {
            for (int j = 0; j < Arr.length ; j++) {

                if (Arr[i] == Arr[j] && i!=j){
                    System.out.println("true");
                    return true;
                }
            }
        }
        System.out.println("false");
        return false;
    }
    public static double avgCalc(int[] Arr){
        double averages = 0;

        for (int x : Arr){
            averages += x;
        }

        return averages / Arr.length;
    }
    public static int[] arrayOfArrays (int[][] arr){
        int minIndx = 0;
        double minAverage = avgCalc(arr[0]);

        for (int i = 0; i < arr.length; i++) {
            if(avgCalc(arr[i]) < minAverage){
                minAverage = avgCalc(arr[i]);
                minIndx = i;
            }

        }
        return arr[minIndx];
    }
//    public void scrapper(String url) {
//        Document doc = null;
//
//        try {
//            doc = Jsoup.connect(url).get();
//        } catch (IOException exception) {
//            System.out.println("some thing went wrong => " + exception.getMessage());
//        }
//
//        assert doc != null;
//        System.out.println(doc.title());
//        Elements newsHeadlines = doc.select("#mp-itn b a");
//        for (Element headline : newsHeadlines) {
//            System.out.printf("%s\n\t%s", headline.attr("title"), headline.absUrl("href"));
//        }
    }

