/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.IOException;
import java.util.*;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }
    public static int[] roll(int n)
    {
        int[] rollArr = new int[n];
        for(int i=0;i<n;i++)
        {
            Random rand = new Random();
            int upperbound = 6;
            int int_random = rand.nextInt(upperbound)+1;
            rollArr[i] = int_random;
        }
        return rollArr;
    }
    public static boolean hasDuplicates(int[] Arr){

        for (int i = 0; i < Arr.length; i++) {
            for (int j = 0; j < Arr.length ; j++) {

                if (Arr[i] == Arr[j] && i!=j){
                    System.out.println("true");
                    return true;
                }
            }
        }
        System.out.println("false");
        return false;
    }
    public static double avgCalc(int[] Arr){
        double averages = 0;

        for (int x : Arr){
            averages += x;
        }

        return averages / Arr.length;
    }
    public static int[] arrayOfArrays (int[][] arr){
        int minIndx = 0;
        double minAverage = avgCalc(arr[0]);

        for (int i = 0; i < arr.length; i++) {
            if(avgCalc(arr[i]) < minAverage){
                minAverage = avgCalc(arr[i]);
                minIndx = i;
            }

        }
        return arr[minIndx];
    }

    //************ lab03features **************************************
    public static String temperaturesHashSet (int[][] weeklyMonthTempArr){

        String neverSaw = "Never saw temperature: ";

        //HashSet definition
        HashSet<Integer> readingTemperatures = new HashSet<>();

        //StringBuilder to build the string that will be printed
        StringBuilder strToPrint = new StringBuilder();


        //Adds temperature values into HashSet
        for (int i = 0; i < weeklyMonthTempArr.length; i++) {
            for (int j = 0; j < weeklyMonthTempArr[i].length ; j++) {
                readingTemperatures.add(weeklyMonthTempArr[i][j]);
            }
        }
        //casting Collections.min because it returns Object value type
        int min = (int)Collections.min(readingTemperatures);
        int max = (int)Collections.max(readingTemperatures);

        // adding and appending new parts on string that was creating using stringBuilder
        strToPrint.append("High: ").append(max).append(System.getProperty("line.separator"));
        strToPrint.append("Low: ").append(min).append(System.getProperty("line.separator"));

        //adding the neverSaw temperature on string that was creating using stringBuilder
        for (int i = min; i <  max ; i++) {

            if(!readingTemperatures.contains(i)){

                strToPrint.append(neverSaw).append(i).append(System.getProperty("line.separator"));
            }

        }
        //used toString because stringBuilder returns Object value type
        return strToPrint.toString();
    }

    public static String tally(List<String> votes){
        //need to tally how many times an item in my array list shows up and return who got the most votes

        int maxVotes = 0;
        String winner = " ";

        for (String name : votes) {
            // Collections.frequency(List, item) how many times (item) is in List
            int numOfVotes = Collections.frequency(votes, name);

            if(numOfVotes > maxVotes){
                maxVotes = numOfVotes;
                winner = name;
            }
        }

        return  winner + " received the most votes!";
    }
}

